include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
      #- java-mvn.yml
    ref: main
  - local: "/includes/java-mvn.yml"

cache:
  paths:
    - .m2/repository/
    - node_modules

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${IMAGE_REPOSITORY}"
  REMOTE_DOCKER_HUB_REGISTRY: "${REGISTRY_HOST}/dockerhub"

stages:
  - read-secret
  - test-app
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

test-app:
  variables:
    BUILD_IMAGE_NAME: "${REMOTE_DOCKER_HUB_REGISTRY}/maven:3.8-openjdk-17"
    WORKING_DIR: .
  stage: test-app
  extends:
    - .java:sonar
  allow_failure: true

docker-build:
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: java-demo
    EXTRA_BUILD_ARGS: "--build-arg PROJECT_PATH=$PROJECT_PATH --build-arg NEXUS_USERNAME=$NEXUS_USERNAME --build-arg NEXUS_PASSWORD=$NEXUS_PASSWORD"
  stage: docker-build
  before_script:
    - cp "$MVN_CONFIG_FILE" settings.xml
    # need to copy internal-ca.crt to the working dir for kaniko docker build
    - if [ ! -z $CA_BUNDLE ]; then cp $CA_BUNDLE ./internal-ca.crt; else touch ./internal-ca.crt; fi
  extends:
    - .kaniko:simple-build-push